#!/usr/bin/env python3
"""Generate committed documentation from FastMCP and skill metadata."""

from __future__ import annotations

import argparse
import asyncio
import difflib
import json
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from mcp.server.fastmcp import FastMCP
from mcp.types import Tool


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from apolo_mcp.policy import HIGH_RISK_ENV, POLICY_FILE_ENV  # noqa: E402
from apolo_mcp.tool_registry import TOOL_REGISTRARS  # noqa: E402
from scripts.install_skills import SKILLS  # noqa: E402


GENERATED_HEADER = (
    "<!-- Generated by build-tools/generate-docs.py. "
    "Edit build-tools/docs-templates and run `make docs`. -->\n\n"
)


@dataclass(frozen=True)
class Document:
    template: Path
    output: Path
    values: dict[str, str]


def _json(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False)


def _description(value: str | None, subject: str) -> str:
    if not value or not value.strip():
        raise ValueError(f"{subject} has no description")
    return " ".join(value.split())


def _classification(tool: Tool) -> str:
    annotations = tool.annotations
    if annotations is None:
        raise ValueError(f"tool {tool.name!r} has no annotations")
    flags = (
        annotations.readOnlyHint,
        annotations.destructiveHint,
        annotations.idempotentHint,
        annotations.openWorldHint,
    )
    if not all(isinstance(flag, bool) for flag in flags):
        raise ValueError(f"tool {tool.name!r} has incomplete annotations")
    if annotations.readOnlyHint:
        if annotations.destructiveHint:
            raise ValueError(f"tool {tool.name!r} is both read-only and destructive")
        return "read-only"
    if annotations.destructiveHint:
        return "destructive"
    if tool.name.startswith("plan_") and annotations.openWorldHint is False:
        return "planning"
    return "write"


async def collect_tools() -> list[tuple[str, Tool, str]]:
    """Collect public FastMCP metadata in canonical module/tool order."""
    result: list[tuple[str, Tool, str]] = []
    seen: set[str] = set()
    for group, register in TOOL_REGISTRARS:
        registry = FastMCP(f"apolo-docs-{group.lower().replace(' ', '-')}")
        register(registry)
        for tool in await registry.list_tools():
            if tool.name in seen:
                raise ValueError(f"duplicate registered tool: {tool.name}")
            seen.add(tool.name)
            _description(tool.description, f"tool {tool.name!r}")
            if not isinstance(tool.inputSchema, dict) or not isinstance(
                tool.outputSchema, dict
            ):
                raise ValueError(f"tool {tool.name!r} has incomplete schemas")
            result.append((group, tool, _classification(tool)))
    return result


def _tool_list(tools: list[tuple[str, Tool, str]], classification: str) -> str:
    selected = [
        f"- [`{tool.name}`](../capabilities/tools.md#{tool.name})"
        f" — {_description(tool.description, tool.name)}"
        for _, tool, kind in tools
        if kind == classification
    ]
    if not selected:
        raise ValueError(f"no {classification} tools were registered")
    return "\n".join(selected)


def render_tools(tools: list[tuple[str, Tool, str]]) -> str:
    grouped: dict[str, list[tuple[Tool, str]]] = defaultdict(list)
    for group, tool, classification in tools:
        grouped[group].append((tool, classification))
    sections: list[str] = []
    for group, _ in TOOL_REGISTRARS:
        sections.append(f"## {group}")
        for tool, classification in grouped[group]:
            annotations = tool.annotations
            assert annotations is not None
            sections.extend(
                [
                    f"### `{tool.name}`",
                    _description(tool.description, tool.name),
                    f"**Operation type:** {classification}",
                    "**Annotations:** "
                    f"read-only `{str(annotations.readOnlyHint).lower()}`, "
                    f"destructive `{str(annotations.destructiveHint).lower()}`, "
                    f"idempotent `{str(annotations.idempotentHint).lower()}`, "
                    f"open-world `{str(annotations.openWorldHint).lower()}`",
                    f"**Input schema:**\n\n```json\n{_json(tool.inputSchema)}\n```",
                    f"**Output schema:**\n\n```json\n{_json(tool.outputSchema)}\n```",
                ]
            )
    return "\n\n".join(sections)


def _frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"skill has no YAML frontmatter: {path}")
    try:
        raw = text.split("---\n", 2)[1]
    except IndexError as error:
        raise ValueError(f"skill has invalid YAML frontmatter: {path}") from error
    value = yaml.safe_load(raw)
    if not isinstance(value, dict):
        raise ValueError(f"skill has invalid YAML frontmatter: {path}")
    return value


def render_skills() -> str:
    sections: list[str] = []
    for name in SKILLS:
        root = ROOT / "skills" / name
        metadata = _frontmatter(root / "SKILL.md")
        openai = yaml.safe_load(
            (root / "agents" / "openai.yaml").read_text(encoding="utf-8")
        )
        interface = openai.get("interface") if isinstance(openai, dict) else None
        if metadata.get("name") != name:
            raise ValueError(f"skill directory/frontmatter name mismatch: {name}")
        if not isinstance(interface, dict):
            raise ValueError(f"skill {name!r} has no OpenAI interface metadata")
        description = _description(metadata.get("description"), f"skill {name!r}")
        display_name = _description(
            interface.get("display_name"), f"skill {name!r} display name"
        )
        short = _description(
            interface.get("short_description"), f"skill {name!r} short description"
        )
        prompt = _description(
            interface.get("default_prompt"), f"skill {name!r} default prompt"
        )
        if f"${name}" not in prompt:
            raise ValueError(f"skill {name!r} default prompt does not invoke the skill")
        sections.append(
            f"## [{display_name}](../../skills/{name}/SKILL.md)\n\n"
            f"**Skill name:** `{name}`\n\n"
            f"**Client summary:** {short}\n\n"
            f"{description}"
        )
    return "\n\n".join(sections)


def _render(document: Document) -> str:
    template = document.template.read_text(encoding="utf-8")
    try:
        body = template.format(**document.values)
    except KeyError as error:
        raise ValueError(
            f"unresolved template marker in {document.template}: {error}"
        ) from error
    return GENERATED_HEADER + body.rstrip() + "\n"


def _update(document: Document, *, check: bool) -> bool:
    expected = _render(document)
    actual = (
        document.output.read_text(encoding="utf-8") if document.output.exists() else ""
    )
    if actual == expected:
        return True
    if check:
        print(
            "".join(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=str(document.output),
                    tofile=f"{document.output} (generated)",
                )
            ),
            end="",
        )
        return False
    document.output.parent.mkdir(parents=True, exist_ok=True)
    document.output.write_text(expected, encoding="utf-8")
    print(f"generated {document.output.relative_to(ROOT)}")
    return True


async def generate(*, check: bool) -> int:
    tools = await collect_tools()
    documents = (
        Document(
            ROOT / "build-tools" / "docs-templates" / "safety.md",
            ROOT / "docs" / "getting-started" / "safety.md",
            {
                "high_risk_env": HIGH_RISK_ENV,
                "policy_file_env": POLICY_FILE_ENV,
                "read_only_tools": _tool_list(tools, "read-only"),
                "planning_tools": _tool_list(tools, "planning"),
                "write_tools": _tool_list(tools, "write"),
                "destructive_tools": _tool_list(tools, "destructive"),
            },
        ),
        Document(
            ROOT / "build-tools" / "docs-templates" / "tools.md",
            ROOT / "docs" / "capabilities" / "tools.md",
            {"tool_reference": render_tools(tools)},
        ),
        Document(
            ROOT / "build-tools" / "docs-templates" / "skills.md",
            ROOT / "docs" / "capabilities" / "skills.md",
            {"skill_reference": render_skills()},
        ),
    )
    current = [_update(item, check=check) for item in documents]
    return 0 if all(current) else 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="diff stale outputs")
    args = parser.parse_args()
    return asyncio.run(generate(check=args.check))


if __name__ == "__main__":
    raise SystemExit(main())
