#!/usr/bin/env python3
"""Generate committed documentation from FastMCP and skill metadata."""

from __future__ import annotations

import argparse
import asyncio
import difflib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from mcp.server.fastmcp import FastMCP
from mcp.types import Tool


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from apolo_mcp.catalog import CAPABILITY_SPECS, SKILL_SPECS  # noqa: E402
from apolo_mcp.ledger import LEDGER_ENV  # noqa: E402
from apolo_mcp.policy import POLICY_MODE_ENV  # noqa: E402


GENERATED_HEADER = (
    "<!-- Generated by build-tools/generate-docs.py; do not edit directly. "
    "Update its canonical source or build-tools/docs-templates, then run `make docs`. "
    "-->\n\n"
)
TEMPLATE_FIELD = re.compile(r"\{([a-z][a-z_]*)\}")


@dataclass(frozen=True)
class Document:
    template: Path
    output: Path
    values: dict[str, str]


@dataclass(frozen=True)
class InlineDocument:
    output: Path
    body: str


def _json(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False)


def _description(value: str | None, subject: str) -> str:
    if not value or not value.strip():
        raise ValueError(f"{subject} has no description")
    return " ".join(value.split())


def _render_template(path: Path, values: dict[str, str]) -> str:
    text = path.read_text(encoding="utf-8")
    for name, value in values.items():
        marker = "{" + name + "}"
        if marker not in text:
            raise ValueError(f"missing template marker {marker} in {path}")
        text = text.replace(marker, value)
    unresolved = TEMPLATE_FIELD.search(text)
    if unresolved is not None:
        raise ValueError(f"unresolved template marker {unresolved.group(0)} in {path}")
    return text


def _classification(tool: Tool) -> str:
    annotations = tool.annotations
    if annotations is None:
        raise ValueError(f"tool {tool.name!r} has no annotations")
    flags = (
        annotations.readOnlyHint,
        annotations.destructiveHint,
        annotations.idempotentHint,
        annotations.openWorldHint,
    )
    if not all(isinstance(flag, bool) for flag in flags):
        raise ValueError(f"tool {tool.name!r} has incomplete annotations")
    if annotations.readOnlyHint:
        if annotations.destructiveHint:
            raise ValueError(f"tool {tool.name!r} is both read-only and destructive")
        return "read-only"
    if annotations.destructiveHint:
        return "destructive"
    if tool.name.startswith("plan_") and annotations.openWorldHint is False:
        return "planning"
    return "write"


async def collect_tools() -> list[tuple[str, Tool, str]]:
    """Collect public FastMCP metadata in canonical module/tool order."""
    result: list[tuple[str, Tool, str]] = []
    seen: set[str] = set()
    for capability in CAPABILITY_SPECS:
        group = capability.title
        registry = FastMCP(f"apolo-docs-{capability.slug}")
        capability.register(registry)
        for tool in await registry.list_tools():
            if tool.name in seen:
                raise ValueError(f"duplicate registered tool: {tool.name}")
            seen.add(tool.name)
            _description(tool.description, f"tool {tool.name!r}")
            if not isinstance(tool.inputSchema, dict) or not isinstance(
                tool.outputSchema, dict
            ):
                raise ValueError(f"tool {tool.name!r} has incomplete schemas")
            result.append((group, tool, _classification(tool)))
    return result


def _group_slug(group: str) -> str:
    return next(item.slug for item in CAPABILITY_SPECS if item.title == group)


OPERATION_LABELS = {
    "read-only": '<mark style="background-color: blue;">Read-only</mark>',
    "planning": '<mark style="background-color: green;">Local planning</mark>',
    "write": '<mark style="background-color: green;">Write</mark>',
    "destructive": ('<mark style="background-color: yellow;">Destructive write</mark>'),
}


def render_tool_group(tools: list[tuple[str, Tool, str]], group: str) -> str:
    sections: list[str] = []
    for tool_group, tool, classification in tools:
        if tool_group != group:
            continue
        annotations = tool.annotations
        assert annotations is not None
        sections.extend(
            [
                f"## `{tool.name}`",
                _description(tool.description, tool.name),
                f"**Operation type:** {OPERATION_LABELS[classification]}",
                "**Annotations:** "
                f"read-only `{str(annotations.readOnlyHint).lower()}`, "
                f"destructive `{str(annotations.destructiveHint).lower()}`, "
                f"idempotent `{str(annotations.idempotentHint).lower()}`, "
                f"open-world `{str(annotations.openWorldHint).lower()}`",
                f"**Input schema:**\n\n```json\n{_json(tool.inputSchema)}\n```",
                f"**Output schema:**\n\n```json\n{_json(tool.outputSchema)}\n```",
            ]
        )
    return "\n\n".join(sections)


def render_tool_index() -> str:
    return "\n".join(
        f"- [{item.title}]({item.slug}.md) — {item.description}"
        for item in CAPABILITY_SPECS
    )


def _frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"skill has no YAML frontmatter: {path}")
    try:
        raw = text.split("---\n", 2)[1]
    except IndexError as error:
        raise ValueError(f"skill has invalid YAML frontmatter: {path}") from error
    value = yaml.safe_load(raw)
    if not isinstance(value, dict):
        raise ValueError(f"skill has invalid YAML frontmatter: {path}")
    return value


def _skill_instructions(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"skill has no YAML frontmatter: {path}")
    try:
        return text.split("---\n", 2)[2].lstrip()
    except IndexError as error:
        raise ValueError(f"skill has invalid YAML frontmatter: {path}") from error


def render_skills() -> str:
    sections: list[str] = []
    for skill in SKILL_SPECS:
        root = ROOT / "skills" / skill.name
        metadata = _frontmatter(root / "SKILL.md")
        openai = yaml.safe_load(
            (root / "agents" / "openai.yaml").read_text(encoding="utf-8")
        )
        interface = openai.get("interface") if isinstance(openai, dict) else None
        if metadata.get("name") != skill.name:
            raise ValueError(f"skill directory/frontmatter name mismatch: {skill.name}")
        if not isinstance(interface, dict):
            raise ValueError(f"skill {skill.name!r} has no OpenAI interface metadata")
        description = _description(metadata.get("description"), f"skill {skill.name!r}")
        display_name = _description(
            interface.get("display_name"), f"skill {skill.name!r} display name"
        )
        if display_name != skill.display_name:
            raise ValueError(f"skill {skill.name!r} display name differs from catalog")
        short = _description(
            interface.get("short_description"),
            f"skill {skill.name!r} short description",
        )
        prompt = _description(
            interface.get("default_prompt"), f"skill {skill.name!r} default prompt"
        )
        if f"${skill.name}" not in prompt:
            raise ValueError(
                f"skill {skill.name!r} default prompt does not invoke the skill"
            )
        sections.append(
            f"## [{display_name}](skills/{skill.name}/README.md)\n\n"
            f"**Skill name:** `{skill.name}`\n\n"
            f"**Client summary:** {short}\n\n"
            f"{description}"
        )
    return "\n\n".join(sections)


def _render(document: Document | InlineDocument) -> str:
    body = (
        _render_template(document.template, document.values)
        if isinstance(document, Document)
        else document.body
    )
    return GENERATED_HEADER + body.rstrip() + "\n"


def _update(document: Document | InlineDocument, *, check: bool) -> bool:
    expected = _render(document)
    actual = (
        document.output.read_text(encoding="utf-8") if document.output.exists() else ""
    )
    if actual == expected:
        return True
    if check:
        print(
            "".join(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=str(document.output),
                    tofile=f"{document.output} (generated)",
                )
            ),
            end="",
        )
        return False
    document.output.parent.mkdir(parents=True, exist_ok=True)
    document.output.write_text(expected, encoding="utf-8")
    print(f"generated {document.output.relative_to(ROOT)}")
    return True


async def generate(*, check: bool) -> int:
    tools = await collect_tools()
    installation = ROOT / "build-tools" / "docs-templates" / "installation.md"
    rnd_runtime = _render_template(
        ROOT / "build-tools" / "docs-templates" / "rnd-runtime.md", {}
    )
    skill_installation = (
        ROOT / "build-tools" / "docs-templates" / "skill-installation.md"
    )
    documents: list[Document | InlineDocument] = [
        Document(
            installation,
            ROOT / "docs" / "getting-started" / "installation.md",
            {},
        ),
        Document(
            ROOT / "build-tools" / "docs-templates" / "full-mode-service-account.md",
            ROOT / "docs" / "guides" / "full-mode-service-account.md",
            {"rnd_runtime": rnd_runtime},
        ),
        Document(
            ROOT / "build-tools" / "docs-templates" / "safety.md",
            ROOT / "docs" / "getting-started" / "safety.md",
            {
                "policy_mode_env": POLICY_MODE_ENV,
                "ledger_env": LEDGER_ENV,
            },
        ),
        Document(
            ROOT / "build-tools" / "docs-templates" / "tools-index.md",
            ROOT / "docs" / "capabilities" / "tools" / "README.md",
            {"tool_groups": render_tool_index()},
        ),
        Document(
            ROOT / "build-tools" / "docs-templates" / "skills.md",
            ROOT / "docs" / "capabilities" / "skills.md",
            {"skill_reference": render_skills()},
        ),
        Document(
            skill_installation,
            ROOT
            / "skills"
            / "apolo-rnd-session-operate"
            / "references"
            / "installation.md",
            {
                "setup_skill_reference": (
                    "[packaged Apolo R&D Session Setup skill]"
                    "(../../apolo-rnd-session-setup/SKILL.md)"
                ),
                "rnd_runtime": rnd_runtime,
            },
        ),
        Document(
            skill_installation,
            ROOT
            / "docs"
            / "capabilities"
            / "skills"
            / "apolo-rnd-session-operate"
            / "references"
            / "installation.md",
            {
                "setup_skill_reference": (
                    "[Apolo R&D Session Setup skill reference]"
                    "(../../apolo-rnd-session-setup/README.md)"
                ),
                "rnd_runtime": rnd_runtime,
            },
        ),
    ]
    documents.extend(
        Document(
            ROOT / "build-tools" / "docs-templates" / "tool-group.md",
            ROOT / "docs" / "capabilities" / "tools" / f"{capability.slug}.md",
            {
                "group": capability.title,
                "tool_reference": render_tool_group(tools, capability.title),
            },
        )
        for capability in CAPABILITY_SPECS
    )
    for skill in SKILL_SPECS:
        source_root = ROOT / "skills" / skill.name
        output_root = ROOT / "docs" / "capabilities" / "skills" / skill.name
        documents.append(
            InlineDocument(
                output_root / "README.md",
                _skill_instructions(source_root / "SKILL.md"),
            )
        )
        reference_root = source_root / "references"
        if not reference_root.is_dir():
            continue
        for reference in sorted(reference_root.glob("*.md")):
            if skill.name == "apolo-rnd-session-operate" and reference.name == (
                "installation.md"
            ):
                continue
            documents.append(
                InlineDocument(
                    output_root / "references" / reference.name,
                    reference.read_text(encoding="utf-8"),
                )
            )
    current = [_update(item, check=check) for item in documents]
    return 0 if all(current) else 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="diff stale outputs")
    args = parser.parse_args()
    return asyncio.run(generate(check=args.check))


if __name__ == "__main__":
    raise SystemExit(main())
